server:
  port: 8000
  
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    user:
      name: user
      password: 1111
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/ 
    suffix: .html
    cache: false
    mode: HTML